services:
  app:
    image: sveltekit-template:latest
    pull_policy: never
    container_name: myapp_container
    env_file:
      - .env
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${PORT}:${PORT}'
    volumes:
      - appdata:/app
      - /app/node_modules
      - /app/.svelte-kit
      - /app/build
volumes:
  appdata:
