// Auto-generated by FeatureRegistry - DO NOT EDIT
// This file will be regenerated when features are registered

/**
 * All registered feature names
 */
export type FeatureName = never;

/**
 * Feature scope type map
 * Each feature maps to its required scope object
 */
export interface FeatureScopes {
	// No features registered yet
}

/**
 * Feature metadata
 */
export const FEATURE_METADATA = {
	// No features registered yet
} as const;
