/* 
This file is generated by the supabase-gen script. Do not edit this file directly.
*/

import { z } from 'zod';

export const schemas = {
	core: {
		account_notification: {
			Row: z.object({
				account_id: z.string(),
				archived: z.boolean(),
				created_at: z.string(),
				icon: z.string(),
				icon_type: z.string(),
				id: z.string(),
				link: z.string().nullable(),
				message: z.string(),
				read: z.boolean(),
				severity: z.string(),
				title: z.string()
			}),
			Insert: z.object({
				account_id: z.string(),
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				icon: z.string(),
				icon_type: z.string(),
				id: z.string().optional(),
				link: z.string().nullable().optional(),
				message: z.string(),
				read: z.boolean().optional(),
				severity: z.string(),
				title: z.string()
			}),
			Update: z.object({
				account_id: z.string().optional(),
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				icon: z.string().optional(),
				icon_type: z.string().optional(),
				id: z.string().optional(),
				link: z.string().nullable().optional(),
				message: z.string().optional(),
				read: z.boolean().optional(),
				severity: z.string().optional(),
				title: z.string().optional()
			})
		},
		admin: {
			Row: z.object({ archived: z.boolean(), created_at: z.string(), id: z.string() }),
			Insert: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional()
			}),
			Update: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional()
			})
		},
		cached_request: {
			Row: z.object({
				archived: z.boolean(),
				created_at: z.string(),
				headers: z.string(),
				id: z.string(),
				response: z.string(),
				status: z.number(),
				ttl: z.number(),
				url: z.string()
			}),
			Insert: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				headers: z.string(),
				id: z.string().optional(),
				response: z.string(),
				status: z.number(),
				ttl: z.number(),
				url: z.string()
			}),
			Update: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				headers: z.string().optional(),
				id: z.string().optional(),
				response: z.string().optional(),
				status: z.number().optional(),
				ttl: z.number().optional(),
				url: z.string().optional()
			})
		},
		profile: {
			Row: z.object({
				archived: z.boolean(),
				created_at: z.string(),
				email: z.string(),
				first_name: z.string(),
				id: z.string(),
				last_name: z.string(),
				username: z.string()
			}),
			Insert: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				email: z.string(),
				first_name: z.string(),
				id: z.string(),
				last_name: z.string(),
				username: z.string()
			}),
			Update: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				email: z.string().optional(),
				first_name: z.string().optional(),
				id: z.string().optional(),
				last_name: z.string().optional(),
				username: z.string().optional()
			})
		},
		role: {
			Row: z.object({
				archived: z.boolean(),
				color: z.string(),
				created_at: z.string(),
				description: z.string(),
				id: z.string(),
				name: z.string()
			}),
			Insert: z.object({
				archived: z.boolean().optional(),
				color: z.string(),
				created_at: z.string().optional(),
				description: z.string(),
				id: z.string().optional(),
				name: z.string()
			}),
			Update: z.object({
				archived: z.boolean().optional(),
				color: z.string().optional(),
				created_at: z.string().optional(),
				description: z.string().optional(),
				id: z.string().optional(),
				name: z.string().optional()
			})
		},
		role_account: {
			Row: z.object({
				account: z.string().nullable(),
				archived: z.boolean(),
				created_at: z.string(),
				id: z.string(),
				role: z.string().nullable()
			}),
			Insert: z.object({
				account: z.string().nullable().optional(),
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional(),
				role: z.string().nullable().optional()
			}),
			Update: z.object({
				account: z.string().nullable().optional(),
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional(),
				role: z.string().nullable().optional()
			})
		},
		session: {
			Row: z.object({
				account_id: z.string().nullable(),
				archived: z.boolean(),
				created_at: z.string(),
				id: z.string(),
				prev_url: z.string().nullable()
			}),
			Insert: z.object({
				account_id: z.string().nullable().optional(),
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional(),
				prev_url: z.string().nullable().optional()
			}),
			Update: z.object({
				account_id: z.string().nullable().optional(),
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional(),
				prev_url: z.string().nullable().optional()
			})
		},
		session_tab: {
			Row: z.object({
				archived: z.boolean(),
				created_at: z.string(),
				id: z.string(),
				session_id: z.string(),
				url: z.string()
			}),
			Insert: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional(),
				session_id: z.string(),
				url: z.string()
			}),
			Update: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional(),
				session_id: z.string().optional(),
				url: z.string().optional()
			})
		}
	},
	public: {
		_template: {
			Row: z.object({ archived: z.boolean(), created_at: z.string(), id: z.string() }),
			Insert: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional()
			}),
			Update: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional()
			})
		}
	},
	test: {
		join_test: {
			Row: z.object({
				archived: z.boolean(),
				created_at: z.string(),
				id: z.number(),
				test_id: z.string().nullable()
			}),
			Insert: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.number().optional(),
				test_id: z.string().nullable().optional()
			}),
			Update: z.object({
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.number().optional(),
				test_id: z.string().nullable().optional()
			})
		},
		test: {
			Row: z.object({
				age: z.number(),
				archived: z.boolean(),
				created_at: z.string(),
				id: z.string(),
				name: z.string()
			}),
			Insert: z.object({
				age: z.number(),
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional(),
				name: z.string()
			}),
			Update: z.object({
				age: z.number().optional(),
				archived: z.boolean().optional(),
				created_at: z.string().optional(),
				id: z.string().optional(),
				name: z.string().optional()
			})
		}
	}
} as const;
